name: resilient-rs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd resilient-rs
          cargo build --verbose
      - name: Check formatting
        run: |
          cd resilient-rs
          cargo fmt --check
      - name: Run tests
        run: |
          cd resilient-rs
          cargo test --verbose

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success' && github.actor == vars.RELEASE_USER

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cargo install cargo-release

      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd resilient-rs
          echo "Releasing a version..."
          cargo release --execute

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd resilient-rs
          cargo publish
